brew "bat"
brew "fd"
brew "fish"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "gnupg"
brew "helm"
brew "hwatch"
brew "jq"
brew "k9s"
brew "lego"
brew "markdownlint-cli"
brew "marksman"
brew "neovim"
brew "openssl@3"
brew "qrencode"
brew "rcm"
brew "restic"
brew "ripgrep"
brew "starship"
brew "ykman"

tap "dashlane/tap"
brew "dashlane/tap/dashlane-cli"

tap "hashicorp/tap"
brew "hashicorp/tap/vault"

cask "font-fira-code-nerd-font"
cask "google-chrome"
cask "visual-studio-code"
